### ISSUE TITLE
Edit names

### ISSUE THREAD

**Issue by Dataweaver42** [krypto5863/COM3D2.CheatMenu#1]
I want to be able to edit the names of Extra Maids: I'm using the Japanese version of the game, but want to use the English versions of their names. I can't do that via Edit Maid, because the Profile tab is disabled; so the script that allows you to change a maid's name in that manner doesn't help with Extra Maids. 

Could you add an option on CheatMenu that lets me alter any maid's name, without having to go to the Editor to do so?

**Comment by krypto5863** [comment]
Eh, extra maids are uber useless anyways. I would, but I also don't know if their names are tied to anything special like dialogue or something other. So probably won't.
